import { DashboardData, Exercise, DayTemplate } from '@/types'

export const PLACEHOLDER_AI_MESSAGE =
    "You slept 7h and you're feeling good — perfect day for a push session. Try 135 lbs on bench today."

export const EXERCISE_LIBRARY: Exercise[] = [
    // PUSH — chest
    {
        id: 'bench-press',
        name: 'Bench Press',
        dayType: ['push'],
        muscleGroups: ['chest', 'shoulders', 'triceps'],
        primaryMuscle: 'chest',
        equipment: ['barbell'],
        movementType: 'compound',
    },
    {
        id: 'incline-bench-press',
        name: 'Incline Bench Press',
        dayType: ['push'],
        muscleGroups: ['chest', 'shoulders', 'triceps'],
        primaryMuscle: 'chest',
        equipment: ['barbell', 'dumbbell'],
        movementType: 'compound',
    },
    {
        id: 'dumbbell-fly',
        name: 'Dumbbell Fly',
        dayType: ['push'],
        muscleGroups: ['chest'],
        primaryMuscle: 'chest',
        equipment: ['dumbbell'],
        movementType: 'isolation',
    },
    {
        id: 'cable-crossover',
        name: 'Cable Crossover',
        dayType: ['push'],
        muscleGroups: ['chest'],
        primaryMuscle: 'chest',
        equipment: ['cable'],
        movementType: 'isolation',
    },
    {
        id: 'push-up',
        name: 'Push Up',
        dayType: ['push', 'full body'],
        muscleGroups: ['chest', 'triceps', 'shoulders'],
        primaryMuscle: 'chest',
        equipment: ['bodyweight'],
        movementType: 'compound',
    },
    // PUSH — shoulders
    {
        id: 'overhead-press',
        name: 'Overhead Press',
        dayType: ['push'],
        muscleGroups: ['shoulders', 'triceps'],
        primaryMuscle: 'shoulders',
        equipment: ['barbell', 'dumbbell'],
        movementType: 'compound',
    },
    {
        id: 'lateral-raise',
        name: 'Lateral Raise',
        dayType: ['push'],
        muscleGroups: ['shoulders'],
        primaryMuscle: 'shoulders',
        equipment: ['dumbbell', 'cable'],
        movementType: 'isolation',
    },
    {
        id: 'front-raise',
        name: 'Front Raise',
        dayType: ['push'],
        muscleGroups: ['shoulders'],
        primaryMuscle: 'shoulders',
        equipment: ['dumbbell', 'barbell'],
        movementType: 'isolation',
    },
    // PUSH — triceps
    {
        id: 'tricep-dips',
        name: 'Tricep Dips',
        dayType: ['push'],
        muscleGroups: ['triceps', 'chest'],
        primaryMuscle: 'triceps',
        equipment: ['bodyweight'],
        movementType: 'compound',
    },
    {
        id: 'tricep-pushdown',
        name: 'Tricep Pushdown',
        dayType: ['push'],
        muscleGroups: ['triceps'],
        primaryMuscle: 'triceps',
        equipment: ['cable'],
        movementType: 'isolation',
    },
    {
        id: 'skull-crushers',
        name: 'Skull Crushers',
        dayType: ['push'],
        muscleGroups: ['triceps'],
        primaryMuscle: 'triceps',
        equipment: ['barbell', 'dumbbell'],
        movementType: 'isolation',
    },
    // PULL — back
    {
        id: 'deadlift',
        name: 'Deadlift',
        dayType: ['pull', 'legs'],
        muscleGroups: ['back', 'hamstrings', 'glutes', 'forearms'],
        primaryMuscle: 'back',
        equipment: ['barbell'],
        movementType: 'compound',
    },
    {
        id: 'bent-over-row',
        name: 'Bent Over Row',
        dayType: ['pull'],
        muscleGroups: ['back', 'biceps', 'forearms'],
        primaryMuscle: 'back',
        equipment: ['barbell', 'dumbbell'],
        movementType: 'compound',
    },
    {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        dayType: ['pull'],
        muscleGroups: ['back', 'biceps'],
        primaryMuscle: 'back',
        equipment: ['cable', 'machine'],
        movementType: 'compound',
    },
    {
        id: 'pull-up',
        name: 'Pull Up',
        dayType: ['pull', 'full body'],
        muscleGroups: ['back', 'biceps'],
        primaryMuscle: 'back',
        equipment: ['bodyweight'],
        movementType: 'compound',
    },
    {
        id: 'seated-cable-row',
        name: 'Seated Cable Row',
        dayType: ['pull'],
        muscleGroups: ['back', 'biceps'],
        primaryMuscle: 'back',
        equipment: ['cable'],
        movementType: 'compound',
    },
    {
        id: 'face-pull',
        name: 'Face Pull',
        dayType: ['pull'],
        muscleGroups: ['shoulders', 'back'],
        primaryMuscle: 'back',
        equipment: ['cable'],
        movementType: 'isolation',
    },
    // PULL — biceps
    {
        id: 'barbell-curl',
        name: 'Barbell Curl',
        dayType: ['pull'],
        muscleGroups: ['biceps', 'forearms'],
        primaryMuscle: 'biceps',
        equipment: ['barbell'],
        movementType: 'isolation',
    },
    {
        id: 'dumbbell-curl',
        name: 'Dumbbell Curl',
        dayType: ['pull'],
        muscleGroups: ['biceps', 'forearms'],
        primaryMuscle: 'biceps',
        equipment: ['dumbbell'],
        movementType: 'isolation',
    },
    {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        dayType: ['pull'],
        muscleGroups: ['biceps', 'forearms'],
        primaryMuscle: 'biceps',
        equipment: ['dumbbell'],
        movementType: 'isolation',
    },
    {
        id: 'cable-curl',
        name: 'Cable Curl',
        dayType: ['pull'],
        muscleGroups: ['biceps'],
        primaryMuscle: 'biceps',
        equipment: ['cable'],
        movementType: 'isolation',
    },
    // LEGS
    {
        id: 'squat',
        name: 'Barbell Squat',
        dayType: ['legs'],
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        primaryMuscle: 'quads',
        equipment: ['barbell'],
        movementType: 'compound',
    },
    {
        id: 'romanian-deadlift',
        name: 'Romanian Deadlift',
        dayType: ['legs'],
        muscleGroups: ['hamstrings', 'glutes'],
        primaryMuscle: 'hamstrings',
        equipment: ['barbell', 'dumbbell'],
        movementType: 'compound',
    },
    {
        id: 'leg-press',
        name: 'Leg Press',
        dayType: ['legs'],
        muscleGroups: ['quads', 'glutes'],
        primaryMuscle: 'quads',
        equipment: ['machine'],
        movementType: 'compound',
    },
    {
        id: 'walking-lunge',
        name: 'Walking Lunge',
        dayType: ['legs'],
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        primaryMuscle: 'quads',
        equipment: ['bodyweight', 'dumbbell'],
        movementType: 'compound',
    },
    {
        id: 'leg-curl',
        name: 'Leg Curl',
        dayType: ['legs'],
        muscleGroups: ['hamstrings'],
        primaryMuscle: 'hamstrings',
        equipment: ['machine'],
        movementType: 'isolation',
    },
    {
        id: 'leg-extension',
        name: 'Leg Extension',
        dayType: ['legs'],
        muscleGroups: ['quads'],
        primaryMuscle: 'quads',
        equipment: ['machine'],
        movementType: 'isolation',
    },
    {
        id: 'hip-thrust',
        name: 'Hip Thrust',
        dayType: ['legs'],
        muscleGroups: ['glutes', 'hamstrings'],
        primaryMuscle: 'glutes',
        equipment: ['barbell', 'bodyweight'],
        movementType: 'compound',
    },
    {
        id: 'calf-raise',
        name: 'Calf Raise',
        dayType: ['legs'],
        muscleGroups: ['calves'],
        primaryMuscle: 'calves',
        equipment: ['machine', 'bodyweight'],
        movementType: 'isolation',
    },
    // CARDIO
    {
        id: 'treadmill-run',
        name: 'Treadmill Run',
        dayType: ['cardio'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['machine'],
        movementType: 'compound',
    },
    {
        id: 'outdoor-run',
        name: 'Outdoor Run',
        dayType: ['cardio'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['bodyweight'],
        movementType: 'compound',
    },
    {
        id: 'cycling',
        name: 'Cycling',
        dayType: ['cardio'],
        muscleGroups: ['quads', 'hamstrings', 'calves'],
        primaryMuscle: 'quads',
        equipment: ['machine'],
        movementType: 'compound',
    },
    {
        id: 'stairmaster',
        name: 'Stairmaster',
        dayType: ['cardio'],
        muscleGroups: ['glutes', 'quads', 'calves'],
        primaryMuscle: 'glutes',
        equipment: ['machine'],
        movementType: 'compound',
    },
    {
        id: 'jump-rope',
        name: 'Jump Rope',
        dayType: ['cardio'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['bodyweight'],
        movementType: 'compound',
    },
    // YOGA
    {
        id: 'vinyasa-flow',
        name: 'Vinyasa Flow',
        dayType: ['yoga'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['bodyweight'],
        movementType: 'compound',
        notes: 'Track duration only',
    },
    {
        id: 'yin-yoga',
        name: 'Yin Yoga',
        dayType: ['yoga'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['bodyweight'],
        movementType: 'compound',
        notes: 'Track duration only',
    },
    {
        id: 'power-yoga',
        name: 'Power Yoga',
        dayType: ['yoga'],
        muscleGroups: ['full body'],
        primaryMuscle: 'full body',
        equipment: ['bodyweight'],
        movementType: 'compound',
        notes: 'Track duration only',
    },
    // BODYWEIGHT / CORE — reps-based
    {
        id: 'hanging-leg-raise',
        name: 'Hanging Leg Raise',
        dayType: ['pull', 'full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
    },
    {
        id: 'ab-wheel',
        name: 'Ab Wheel',
        dayType: ['full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
    },
    // BODYWEIGHT / CORE — hold/duration-based
    {
        id: 'plank',
        name: 'Plank',
        dayType: ['full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
    {
        id: 'side-plank',
        name: 'Side Plank',
        dayType: ['full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
    {
        id: 'dead-hang',
        name: 'Dead Hang',
        dayType: ['pull', 'full body'],
        muscleGroups: ['back', 'forearms'],
        primaryMuscle: 'back',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
    {
        id: 'l-sit',
        name: 'L-Sit',
        dayType: ['full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
    {
        id: 'wall-sit',
        name: 'Wall Sit',
        dayType: ['legs', 'full body'],
        muscleGroups: ['quads', 'glutes'],
        primaryMuscle: 'quads',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
    {
        id: 'hollow-body-hold',
        name: 'Hollow Body Hold',
        dayType: ['full body'],
        muscleGroups: ['core'],
        primaryMuscle: 'core',
        equipment: ['bodyweight'],
        movementType: 'isolation',
        exerciseType: 'hold',
    },
]

export const DEFAULT_WEEK_TEMPLATE: DayTemplate[] = [
    { dayOfWeek: 1, label: 'Push Day', dayType: 'push', workoutType: 'strength' },
    { dayOfWeek: 2, label: 'Cardio', dayType: 'cardio', workoutType: 'cardio' },
    { dayOfWeek: 3, label: 'Pull Day', dayType: 'pull', workoutType: 'strength' },
    { dayOfWeek: 4, label: 'Yoga', dayType: 'yoga', workoutType: 'yoga' },
    { dayOfWeek: 5, label: 'Legs Day', dayType: 'legs', workoutType: 'strength' },
    { dayOfWeek: 6, label: 'Rest', dayType: 'rest', workoutType: 'bodyweight' },
    { dayOfWeek: 0, label: 'Rest', dayType: 'rest', workoutType: 'bodyweight' },
]

export const PLACEHOLDER_DASHBOARD: DashboardData = {
    todayWorkout: {
        id: '1',
        date: new Date().toISOString(),
        type: 'strength',
        dayType: 'push',
        name: 'Push Day',
        exercises: [
            { exerciseId: 'bench-press', exerciseName: 'Bench Press', sets: 3, reps: 10, weight: '125 lbs', progressReady: true },
            { exerciseId: 'overhead-press', exerciseName: 'Overhead Press', sets: 3, reps: 10, weight: '65 lbs' },
            { exerciseId: 'tricep-dips', exerciseName: 'Tricep Dips', sets: 3, reps: 12, weight: 'BW' },
        ],
    },
    recentSessions: [
        { id: '2', date: '2026-06-02', type: 'yoga', dayType: 'yoga', name: 'Yoga Flow', duration: 45 },
        { id: '3', date: '2026-05-31', type: 'cardio', dayType: 'cardio', name: 'Morning Run', duration: 32 },
        { id: '4', date: '2026-05-30', type: 'strength', dayType: 'pull', name: 'Pull Day', duration: 55 },
    ],
    currentStreak: 6,
    weeklyGoal: 5,
    weeklyCompleted: 3,
    avgSleep: 6.8,
    lastSleep: { date: new Date().toISOString(), hours: 7, quality: 4 },
    weekSessions: [
        { id: '2', date: '2026-06-02', type: 'yoga', dayType: 'yoga', name: 'Yoga Flow' },
        { id: '1', date: '2026-06-03', type: 'strength', dayType: 'push', name: 'Push Day' },
        null, null, null, null, null,
    ],
}